Repository codeforpdx/dwellingly-app, pull requests merged in 2021-08, with the labels that each got.

#590 Mobile-friendly Bootstrap Tables
  package-lock.json
  package.json
  src/constants/index.js
  src/views/managers/managers.jsx
  src/views/managers/managers.scss
  src/views/managers/managersTableComponents.jsx
  src/views/properties/properties.jsx
  src/views/properties/propertiesTableComponents.jsx
  src/views/tenants/tenants.jsx
  src/views/tenants/tenantsFormStructure.jsx
  src/views/tenants/tenantsTableComponents.jsx
  src/views/tickets/tickets.jsx
  src/views/tickets/ticketsTableComponents.jsx
Labels: FRONTEND

#669 Fix tests
  src/components/Header/header.test.js
  src/components/Header/index.jsx
  src/views/Manager/index.test.js
  src/views/Settings/index.test.js
  src/views/managers/managers.test.js
  src/views/signup/signup.test.js
Labels: ready for review

#673 Issue672 Update favicon
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: ready for review

#611 Issue526 Add ability to create tickets
  src/App.jsx
  src/components/TicketModal/TicketModalDetails.jsx
  src/views/AddTicket/addTicket.jsx
  src/views/AddTicket/addTicket.scss
  src/views/NavigationMenu/navigationMenu.jsx
  src/views/addProperty/addProperty.jsx
  src/views/tickets/tickets.jsx
  src/views/tickets/ticketsTableComponents.jsx
Labels: ready for review, Priority

#676 Add post-build script for heroku
  package.json
Labels: ready for review

#655 Set up system tests
  .github/workflows/system_test.yml
  .gitignore
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/login.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: Testing

#674 Show Property manager names and tenant count on properties grid
  src/views/properties/properties.jsx
Labels: ready for review
